env:
  es2021: true
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended-type-checked
  - plugin:@typescript-eslint/stylistic-type-checked
parser: "@typescript-eslint/parser"
parserOptions:
  ecmaVersion: latest
  sourceType: module
  project: true
plugins:
  - "@typescript-eslint"
  - "simple-import-sort"
ignorePatterns:
  - "node_modules"
  - "jest.config.js"
  - "src/mapping-templates-js"
  - "scorebridge-ts-submodule/react"
  - "scorebridge-ts-submodule/tsSubmoduleLog.ts"
rules:
  "sort-imports": "off"
  "simple-import-sort/imports": "error"
  "simple-import-sort/exports": "error"
#  "import/first": "error",
#  "import/newline-after-import": "error",
#  "import/no-duplicates": "error"

